From docker.repository.esi.adp.com/clientcentral/java:17.0.1-jdk
EXPOSE 8087
copy ./target/springboot-app-0.0.1-SNAPSHOT.jar springboot-app-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","springboot-app-0.0.1-SNAPSHOT.jar"]